
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bernardo SJ
 */
public class carreraEntrenamiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form carreraEntrenamiento
     */
    public JLabel getO1(){
        return o1;
    }
    
    public JLabel getO2(){
        return o2;
    }
    
    public JLabel getO3(){
        return o3;
    }
    public JLabel getMeta(){
        return meta;
    }
   
    public carreraEntrenamiento() {
        initComponents();
       marca.setEnabled(false);
       otra.setEnabled(false);
      this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        o1 = new javax.swing.JLabel();
        o2 = new javax.swing.JLabel();
        meta = new javax.swing.JLabel();
        inicia = new javax.swing.JButton();
        marca = new javax.swing.JButton();
        otra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        o3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        o1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N
        o1.setText("Spirit");

        o2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N
        o2.setText("Zeus");

        meta.setBackground(new java.awt.Color(0, 0, 0));
        meta.setText("meta");

        inicia.setText("Inicia");
        inicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaActionPerformed(evt);
            }
        });

        marca.setText("Marcar");
        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });

        otra.setText("Nuevo entrenamiento");
        otra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otraActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bandera.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CARRERA DE CABALLOS");

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        o3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horse.png"))); // NOI18N
        o3.setText("Tornado");

        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(o2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(o1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel2)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(o3))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(meta))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(inicia)
                .addGap(52, 52, 52)
                .addComponent(marca)
                .addGap(37, 37, 37)
                .addComponent(otra)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(o1)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(o2)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(o3))
                    .addComponent(meta, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicia)
                    .addComponent(marca)
                    .addComponent(otra))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Cronometro2 cr;
    private void iniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaActionPerformed
        o1.setLocation(0,o1.getLocation().y);
        o2.setLocation(0,o2.getLocation().y);
        o3.setLocation(0,o3.getLocation().y);
        Cronometro2.estaFuncionando=false;
        Funcionamiento2 c1=new Funcionamiento2(o1,this);
        c1.setName("Spirit");
        Funcionamiento2 c2=new Funcionamiento2(o2,this);
        c2.setName("Zeus");
        Funcionamiento2 c3=new Funcionamiento2(o3,this);
        c3.setName("Tornado");
        c1.start();
        c2.start();
        c3.start();
        cr=new Cronometro2(this);
        inicia.setEnabled(false);
       marca.setEnabled(true);
       otra.setEnabled(false);
    }//GEN-LAST:event_iniciaActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
          
        cr.marcar();
    }//GEN-LAST:event_marcaActionPerformed

    private void otraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otraActionPerformed
        o1.setLocation(0,o1.getLocation().y);
        o2.setLocation(0,o2.getLocation().y);
        o3.setLocation(0,o3.getLocation().y);
        inicia.setEnabled(true);
        otra.setEnabled(false);
        cr=null;
        CronometrajeCarrera.lminutos.setText("00");
           CronometrajeCarrera.lsegundos.setText("00");
           CronometrajeCarrera.lmilisegundos.setText("000");
        carreraEntrenamiento.inicia.setEnabled(true);
            carreraEntrenamiento.marca.setEnabled(false);
       carreraEntrenamiento.otra.setEnabled(false);
       for(int i=0;i<CronometrajeCarrera.modeloTabla.getRowCount();i++){
           CronometrajeCarrera.modeloTabla.removeRow(i);
           i-=1;
       }
    }//GEN-LAST:event_otraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton inicia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JButton marca;
    private javax.swing.JLabel meta;
    private javax.swing.JLabel o1;
    private javax.swing.JLabel o2;
    private javax.swing.JLabel o3;
    public static javax.swing.JButton otra;
    // End of variables declaration//GEN-END:variables
}
